apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-injunweb-tls
  namespace: gateway
spec:
  secretName: wildcard-injunweb-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . | quote }}
    {{- end }}
