{{- if .Values.storage.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkit-storage
  namespace: buildkit
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.pvc.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
{{- end }}
