apiVersion: v2
name: argocd-workflow
description: argocd-workflow chart for Kubernetes
type: application
version: 1.0.0
appVersion: "v3.6.2"
dependencies:
  - name: argo-workflows
    version: "0.45.2"
    repository: "https://argoproj.github.io/argo-helm"
