apiVersion: v2
name: longhorn
description: longhorn chart for Kubernetes
type: application
version: 1.0.0
appVersion: "v1.9.2"
dependencies:
  - name: longhorn
    version: "1.9.2"
    repository: "https://charts.longhorn.io"
