loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
      size: 20Gi
    config:
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      schema_config:
        configs:
          - from: 2025-01-16
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi

  promtail:
    enabled: true
  grafana:
    enabled: false
  prometheus:
    enabled: false
  filebeat:
    enabled: false
  fluent-bit:
    enabled: false
  logstash:
    enabled: false
  serviceMonitor:
    enabled: true
