apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - intweb
    - intwebsec
  routes:
    - kind: Rule
      match: Host(`argocd.injunweb.com`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.injunweb.com`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-webhook
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
    - intweb
    - intwebsec
  routes:
    - kind: Rule
      match: Host(`argocdwebhook.injunweb.com`) && Path(`/api/webhook`)
      services:
        - name: argocd-server
          port: 80
