apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: harbor-timeout
  namespace: harbor
spec:
  forwardingTimeouts:
    dialTimeout: "1800s"
    responseHeaderTimeout: "1800s"
    idleConnTimeout: "1800s"
